AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ka4-today-bot – Telegram + OpenAI notification Lambda bot

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 120
    MemorySize: 512
    Environment:
      Variables:
        TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
        TELEGRAM_SECURITY_TOKEN: !Ref TelegramSecurityToken
        OPENAI_API_KEY: !Ref OpenAiToken
        OPENAI_PROJECT_ID: !Ref OpenAiProjectId
        OPENAI_ASSISTANT_ID: !Ref OpenAiAssistantId
        DYNAMODB_ENDPOINT: !Ref DynamoDbEndpoint
        MAIN_MESSAGE_QUEUE_URL: !Ref MainMessageQueue

Parameters:
  TelegramBotToken:
    Type: String
    Description: Telegram bot token from BotFather
  TelegramSecurityToken:
    Type: String
    Description: Token used to validate incoming webhook requests
  OpenAiToken:
    Type: String
    Description: OpenAI API key (starts with sk-...)
  OpenAiProjectId:
    Type: String
    Description: Project ID from OpenAI (starts with proj-...)
  OpenAiAssistantId:
    Type: String
    Description: Assistant ID from OpenAI (starts with asst-...)
  OpenAiDefaultPrompt:
    Type: String
    Description: Default prompt that will be sent to OpenAI thread
  DynamoDbEndpoint:
    Type: String
    Description: DynamoDb endpoint address
    Default: ""

Resources:
  #####################################################################
  ##                         Storage                                 ##
  #####################################################################
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stack/storage.yaml
  #####################################################################
  ##                         Functions                               ##
  #####################################################################
  Ka4TodayTelegramWebhook:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ka4today-telegram-webhook-handler
      Handler: src/handlers/ka4TodayTelegramWebhook.handler
      CodeUri: .
      Events:
        Webhook:
          Type: HttpApi
          Properties:
            Path: /ka4-today-webhook
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt MainMessageQueue.Arn

  Ka4TodayAsyncTelegramProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ka4today-async-telegram-processor
      Handler: src/handlers/asyncTelegramProcessor.handler
      CodeUri: .
      Events:
        MessageQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MainMessageQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
            ScalingConfig:
              MaximumConcurrency: 2
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt MainMessageQueue.Arn
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource:
              - !GetAtt StorageStack.Outputs.Ka4TodayUsersTableArn
              - !GetAtt StorageStack.Outputs.UserTrainingScheduleTableArn
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ka4-today-users-training-schedule/index/ScheduleByDay
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - !GetAtt StorageStack.Outputs.Ka4TodayLogTableArn
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:GetItem
            Resource:
              - !GetAtt StorageStack.Outputs.Ka4TodayPromptsTableArn
        - Statement:
            - Sid: ReadExerciseImages
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:HeadObject
              Resource: arn:aws:s3:::ka4-today-exercises/exercises/*

  Ka4TodayCronDailyMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ka4today-cron-daily-message
      Handler: src/handlers/cronDailyMessage.handler
      CodeUri: .
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 3 ? * 2-7 *)  # 2:00 UTC = 5:00 by Kyiv (summer), 03:00 UTC = 05:00 Kyiv (winter)
            #Schedule: rate(3 minutes)
            Enabled: true
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt MainMessageQueue.Arn
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:BatchGetItem
              - dynamodb:GetItem
            Resource:
              - !GetAtt StorageStack.Outputs.Ka4TodayUsersTableArn
              - !GetAtt StorageStack.Outputs.UserTrainingScheduleTableArn
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ka4-today-users/index/ActiveUsersIndex
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ka4-today-users-training-schedule/index/ScheduleByDay

  #####################################################################
  ##                         LogGroups                               ##
  #####################################################################
  TelegramWebhookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ka4today-telegram-webhook-handler
      RetentionInDays: 7
  Ka4TodayAsyncTelegramProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ka4today-async-telegram-processor
      RetentionInDays: 7
  CronDailyMessageLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ka4today-cron-daily-message
      RetentionInDays: 7

  #####################################################################
  ##                         SQS                                     ##
  #####################################################################
  MainMessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ka4today-main-message-queue
      VisibilityTimeout: 130 #  Queue visibility timeout should be > Lambda execution timeout